### PR TITLE
Implement Load Last Opened / Recent Database Features

### PR DESCRIPTION
**Pull request by AlBannaTechno**
### I Implemented Two Options For The Same Feature

* Load Last Opened Database Now `Button`
* Load Last Opened Database On Startup `Checkbox`

### Notes: 

* Application Layout slightly changed

<a href="https://ibb.co/ctRPJmN">1up</a>

<a href="https://ibb.co/5RM0mTh">up2</a>

#### New Feature`Recent List`
<a href="https://ibb.co/fxDYG4s">final-litedb</a>

* Changes Stored in `Setting.Default` section, 

[see How To: Write User Settings at Run Time with C#: Microsoft](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-write-user-settings-at-run-time-with-csharp)

* All Config Settings Management Done Inside `ICSharpCode.TextEditor.Util.AppSettingsManager`, static class and this should be used for future settings operations if we take the same approach for persisting user settings

* Loading last opened DB will use the same settings used when loading the DB first time, eg, `connectionType=Shared|Direct, password,..`

-------

Talking

First, I think we should implement this feature using `LiteDb` itself, so we will gain more flexibility for example when we add a new feature for recently opened files `list`

But this approach will need some extra works

Also, we can Use Registery to persist data, but I do not prefer this approach because we even do not know if the user has permission to write to register or not

anyway, there is a lot of methods to persist data, but I just use this method since it is very easy to implement.

### CODE REVIEW

**Comment by AlBannaTechno** [comment]
@mbdavid 
@lbnascimento 

anyone here ?!!

**Comment by lbnascimento** [comment]
@AlBannaTechno We like your idea, but there are a few issues with your implementation.

First, I think it's better to store the entire connection string (and parse it upon opening) instead of storing individual components. Also, there are a few code style issues, like the `load_last_db_CheckedChanged` method. You should use `camelCase` for private attributes and local variables, everything else should use `PascalCase`.

If you make these changes, we'll accept your PR.

**Comment by AlBannaTechno** [comment]
@lbnascimento thank you for your review, I changed the code to match what you asked

With two notes
* Class `ICSharpCode.TextEditor.Util.Model.ApplicationSettings` designed to use as wide application settings, means when we implement recent opened databases list, we should use it, `i think I will implement it in next few weeks`

* If you run the previous build `my PR before editing` this application may not startup due to a confliction in user. settings, so you should remove this directory `%USERPROFILE%\AppData\Local\LiteDB\`

**Comment by AlBannaTechno** [comment]
@lbnascimento @mbdavid 
No Recent List and Load Last DB Features Implemented
Wait Your review.

**Comment by AlBannaTechno** [comment]
@lbnascimento @mbdavid 10 days left, anyone here.

**Comment by lbnascimento** [comment]
@AlBannaTechno Sorry about noticing this so late, but something happened in your commits that the bundled .exe generated by ILMerge doesn't work anymore. The last commit for which it works is 37c4bcc079af351901e8254e66f50df82e8106e2. There are some commits that don't compile and it stops working in 5d325505f6797198e09071eaf754de114ba9168a.

We intend to release a new version soon, and if we can't figure out what is happening, we'll have to revert this PR.

**Comment by AlBannaTechno** [comment]
@lbnascimento The latest version works on my device, and all other devices in my company
without any issue,m I attached the release version based on the last commit
[Release.zip](https://github.com/mbdavid/LiteDB.Studio/files/6887510/Release.zip)

but i never test it with ILMerge, i will try to test it to figure the problem, thank you.

**Comment by lbnascimento** [comment]
@AlBannaTechno I changed the building system and the bundled .exe is now working again.

**Pull request merged**
